### ISSUE TITLE
Set running headers and footers for all @page styles by default

### ISSUE THREAD

**Issue by arthurattwell** [electricbookworks/electric-book#139]
Hi the moment, running headers and footers are off by default on all `@page`s, and then turned on for `frontmatter` and `chapter`.

The upside of this is that any new page style starts as a blank slate. Sometimes that's nice, like when one adds blank pages: `style: blank` or `style: whatever` creates a blank page.

The downside of this is that if we want some chapter pages to have different headers and footers (e.g. a colour change), we have to define everything about that new `@page` style, with nothing coming from the template styles to help us.

If, instead, we defined the default `@page` the way we currently style `page: chapter`, then it's easier to override particular chapters or chapter pages with new features. And we can turn off `content` in any new `@page` styles created in custom CSS.

**Comment by arthurattwell** [comment]
I now think there is a better approach: we should be able to set a variable that lists all page styles that need headers and/or footers, and then loop through the list to create styles for all those pages, something like this:

```scss
$page-styles-with-headers: chapter !default; // This is our default
$page-styles-with-headers: chapter, anotherpagestyle, yetanotherpagestyle; // This is custom, per book

// Then in _print-page-headers-footers-content.scss:

@mixin page-headers() {
    @top {
      content: "A header"; // etc.
    }
    // etc.
}

@each $page-style in $page-styles-with-headers {
    .#{$page-style} {
        page: $page-style;
    }
    @page #{$page-style} {
        @include page-headers();
    }
}
```
