### ISSUE TITLE
Enable images over double-page-spread

### ISSUE THREAD

**Issue by arthurattwell** [electricbookworks/electric-book#20]
_From @arthurattwell on August 27, 2015 12:35_

Images over a DPS are difficult to do in this framework, but it is possible. It's a bit of a hack, but once we've used it a few times and we feel the method is reliable, we may built it into the framework natively.

Of course, images across a DPS are not an ebook or web issue (if an ereader or browser shows 'pages' as a DPS, we have no control over it anyway). They are only a print issue. The problem is that PrinceXML does not provide a mechanism for placing images (or any element) across a spread. 

In short, what we do is place the image twice, each in a blockquote element. Using PrinceXML's `next` modifier for floats, we float the blockquote elements on the first and second pages of the DPS respectively. Inside each blockquote, we position the image so that, on the left, only the left half of the image shows; and on the right, only the right half of the image shows.

This all depends on placing your image reference in a way that the first blockquote–image falls on a left-hand page.

Here's how to do it:
1. The image itself must be in the right aspect ratio. This method cannot (yet) resize or crop your image for you with CSS. In this example here, the image must be 270×120 (landscape), including an allowance for 5mm bleed.
2. In the markdown text file, place the image twice, each inside a blockquote, and tag the first instance `{:.dps-left}` and the second `{:.dps-right}`.
   
   ``` markdown
   > ![1](images/lion.tif)
   {:.dps-left}
   
   > ![1](images/lion.tif)
   {:.dps-right}
   ```
3. Hide the second instance of the image in any screen or epub CSS:
   
   ``` CSS
   /* Hide second instance of images intended for DPS in print */
   .dps-right { 
     display: none;
   }
   ```
4. In print CSS, use this. Follow the comments to modify sizes to suit your page size and layout:
   
   ``` CSS
   /* DPS images */
   
   blockquote.dps-left {
   float: top;
   margin: -20mm 0 10mm -5mm; /* Here you're aiming to start the image in the page bleed top left */
   width: 135mm; /* Page width plus one side's bleed, e.g. 130mm wide plus 5mm bleed */
   height: 120mm; /* Exact height of the image */
   text-align: left;
   }
   blockquote.dps-right {
   float: top next;
   margin: -20mm 0 10mm -5mm; /* Here you're aiming to place the image in the page bleed top right */
   width: 135mm; /* Page width plus one side's bleed, e.g. 130mm wide plus 5mm bleed */
   height: 120mm; /* Exact height of the image */
   text-align: right;
   }
   blockquote.dps-left p img {
   width: 270mm; /* This must be exactly double the width above */
   max-height: 120mm; /* This must be the same as the height above */
   position: absolute;
   left: -5mm;
   }
   blockquote.dps-right p img {
   width: 270mm; /* Ditto */
   max-height: 120mm; /* Ditto */
   position: absolute;
   right: -5mm;
   }
   ```

That's all based on these page settings. Yours may differ, affecting your margins, heights and widths accordingly:

``` CSS
@page {
    size: 130mm 200mm;
    margin-top: 15mm;
    margin-bottom: 20mm;
    margin-outside: 0;
    margin-inside: 0;
    prince-bleed: 5mm;
    prince-trim: 5mm;
}
```

We've done very little testing with this so far. 

_Copied from original issue: electricbookworks/electric-book-workflow#3_
