### ISSUE TITLE
Add class for tightening line-height

### ISSUE THREAD

**Issue by arthurattwell** [electricbookworks/electric-book#258]
Occasionally we need to adjust line-height of an element to fit it on a page (e.g. a very large table). We could add a `tighten-lines-n` class to the template that would make this easy. Here is the code for PDF, which is probably all we need (there is rarely a need to tighten lines in other formats):

``` scss
// These classes tighten line-height by percentage.
// E.g. `tighten-lines-90` tightens line-height to 90% of the default.
@for $i from 1 through 100 {
	$new-line-height: ($i / 100) * $line-height-default;
	.tighten-lines-#{$i}#{$edition-suffix} {
		line-height: $new-line-height;
	}
}
```
